export default {
  CHANGE: "CHANGE",
<<<<<<< HEAD
  TOGGLE_SIDEBAR: "TOGGLE_SIDEBAR"
=======
  TOGGLE_SIDEBAR: "TOGGLE_SIDEBAR",
  ADD_RESOURCE: "ADD_RESOURCE",
  GET_RESOURCES: "GET_RESOURCES",
  GET_RESOURCES_RESPONSE: "GET_RESOURCES_RESPONSE",
>>>>>>> 099650ac3b038aeef5dbca2b18b9b3b02e8275f1
};
